name: Run end2end tests

on:  
  # We would never need to run this workflow manually, but enabling manual trigger in case we hit some roadblock.
  workflow_dispatch:
    inputs:
      EXECUTION_ENVIRONMENT:
        description: 'Select ENV'
        type: choice
        required: true
        default: 'dev4 internal'
        options:
          - 'dev4 internal'

jobs:
  release:
    name: Release from pushed tag
    runs-on: ubuntu-latest
    steps:         
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl --request GET \
            --url "https://api.github.com/repos/yuriysemen/test_actions/commits/${{ github.ref }}/status" \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            

